//                                                                          //
// Copyright 2016 Mirko Raner                                               //
//                                                                          //
// Licensed under the Apache License, Version 2.0 (the "License");          //
// you may not use this file except in compliance with the License.         //
// You may obtain a copy of the License at                                  //
//                                                                          //
//     http://www.apache.org/licenses/LICENSE-2.0                           //
//                                                                          //
// Unless required by applicable law or agreed to in writing, software      //
// distributed under the License is distributed on an "AS IS" BASIS,        //
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. //
// See the License for the specific language governing permissions and      //
// limitations under the License.                                           //
//                                                                          //
package pro.projo.doubles;

import pro.projo.internal.ProjoFactoryTemplateConfiguration;
import pro.projo.template.annotation.Template;

/**
*
* The {@link pro.projo.doubles.Factory} interface defines Projo's generic factory for objects with 2 fields.
*
* @param <_Artifact_> the artifact type generated by the factory
* @param <_First_> the type of the first field
* @param <_Second_> the type of the second field
*
* @author Mirko Raner
**/
/**/
public interface Factory<_Artifact_, _First_, _Second_> extends pro.projo.Factory
{
    /**/
    /**
    * Creates a new Projo object, using the arguments to initialize the object's fields.
    *
    * @param first the first parameter
    * @param second the second parameter
    * @return a new Projo object
    **/
    _Artifact_ create(_First_ first, _Second_ second);
}
